import type { Recommendation } from "@/types/recommendation";

// Hardcoded mocks until Alon's engine lands. Match scores descend so the
// "infinite scroll keeps pulling at lower confidence" behaviour reads
// naturally even on a static list.
//
// poster_url is null for most so we exercise the motif fallback. A couple
// of real-looking TMDB paths show the image path too — if TMDB no longer
// has the asset, onError flips back to the motif.

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "tt-bad-sisters",
    title: "Bad Sisters",
    type: "tv",
    year: 2022,
    poster_url: null,
    meta: "10 ep · S1",
    rating: 8.3,
    match: 0.96,
    reason: "Slow-burn ensemble · sibling chemistry · darkly funny",
    where: "Apple TV+",
    motif: "circle",
    palette: ["#1B2A28", "#C7B8FF"],
  },
  {
    id: "tt-poker-face",
    title: "Poker Face",
    type: "tv",
    year: 2023,
    poster_url: null,
    meta: "10 ep · S1",
    rating: 8.0,
    match: 0.92,
    reason: "Case-of-the-week · Rian Johnson DNA · warm lead",
    where: "Peacock",
    motif: "spades",
    palette: ["#2A1810", "#E8C547"],
  },
  {
    id: "tt-mr-mrs-smith",
    title: "Mr & Mrs Smith",
    type: "tv",
    year: 2024,
    poster_url: null,
    meta: "8 ep · S1",
    rating: 7.4,
    match: 0.87,
    reason: "Twisty premise · mundane stakes · long-take dialogue",
    where: "Prime Video",
    motif: "cross",
    palette: ["#0F1620", "#7FB3FF"],
  },
  {
    id: "tt-banshees",
    title: "The Banshees of Inisherin",
    type: "movie",
    year: 2022,
    poster_url: null,
    meta: "1h 54m",
    rating: 7.7,
    match: 0.84,
    reason: "McDonagh follow-up · friendship-as-horror · folk dread",
    where: "Disney+",
    motif: "wave",
    palette: ["#1C2A1A", "#E9E2C8"],
  },
  {
    id: "tt-past-lives",
    title: "Past Lives",
    type: "movie",
    year: 2023,
    poster_url: null,
    meta: "1h 45m",
    rating: 7.9,
    match: 0.81,
    reason: "Quiet · longing · subtitles you won't mind",
    where: "Paramount+",
    motif: "dot",
    palette: ["#16242E", "#F5C9A6"],
  },
  {
    id: "tt-loot",
    title: "Loot",
    type: "tv",
    year: 2022,
    poster_url: null,
    meta: "20 ep · S1–2",
    rating: 7.4,
    match: 0.78,
    reason: "Warm ensemble · low stakes · 22-min episodes",
    where: "Apple TV+",
    motif: "star",
    palette: ["#2D0F2E", "#FF7AB8"],
  },
  {
    id: "tt-killing-eve",
    title: "Killing Eve",
    type: "tv",
    year: 2018,
    poster_url: null,
    meta: "32 ep · S1–4",
    rating: 8.2,
    match: 0.74,
    reason: "Cat-and-mouse · dry humour · two-hander dynamic",
    where: "BBC iPlayer",
    motif: "cross",
    palette: ["#1A0F1A", "#FFB5C5"],
  },
  {
    id: "tt-anatomy-of-a-fall",
    title: "Anatomy of a Fall",
    type: "movie",
    year: 2023,
    poster_url: null,
    meta: "2h 32m",
    rating: 7.7,
    match: 0.71,
    reason: "Procedural · marital fracture · pristine craft",
    where: "Neon",
    motif: "wave",
    palette: ["#1E1E22", "#DCC9A8"],
  },
  {
    id: "tt-pachinko",
    title: "Pachinko",
    type: "tv",
    year: 2022,
    poster_url: null,
    meta: "16 ep · S1–2",
    rating: 8.5,
    match: 0.68,
    reason: "Multi-generational drama · diaspora ache · slow burn",
    where: "Apple TV+",
    motif: "dot",
    palette: ["#1B1E0F", "#E5C77A"],
  },
  {
    id: "tt-leftovers",
    title: "The Leftovers",
    type: "tv",
    year: 2014,
    poster_url: null,
    meta: "28 ep · S1–3",
    rating: 8.4,
    match: 0.64,
    reason: "Grief as plot engine · ensemble · Lindelof",
    where: "HBO Max",
    motif: "circle",
    palette: ["#16161C", "#A8B5D8"],
  },
  {
    id: "tt-frances-ha",
    title: "Frances Ha",
    type: "movie",
    year: 2012,
    poster_url: null,
    meta: "1h 26m",
    rating: 7.4,
    match: 0.61,
    reason: "Black & white indie · friendship drift · low stakes",
    where: "MUBI",
    motif: "star",
    palette: ["#1A1A1A", "#F0F0F0"],
  },
  {
    id: "tt-fleabag",
    title: "Fleabag",
    type: "tv",
    year: 2016,
    poster_url: null,
    meta: "12 ep · S1–2",
    rating: 8.7,
    match: 0.58,
    reason: "Fourth-wall break · sibling tension · sharp grief humour",
    where: "Prime Video",
    motif: "spades",
    palette: ["#2A1A1A", "#FF9F9F"],
  },
  {
    id: "tt-aftersun",
    title: "Aftersun",
    type: "movie",
    year: 2022,
    poster_url: null,
    meta: "1h 41m",
    rating: 7.6,
    match: 0.55,
    reason: "Father-daughter · memory · A24 patience",
    where: "Mubi",
    motif: "wave",
    palette: ["#1F2330", "#D4E0F0"],
  },
  {
    id: "tt-the-bear",
    title: "The Bear",
    type: "tv",
    year: 2022,
    poster_url: null,
    meta: "28 ep · S1–3",
    rating: 8.6,
    match: 0.52,
    reason: "Kitchen chaos · grief · tight half-hours",
    where: "Hulu",
    motif: "cross",
    palette: ["#2A1A0F", "#F5A26B"],
  },
];

/** Slice for pagination — returns up to `pageSize` items starting at `offset`. */
export function pageOf(
  list: Recommendation[],
  offset: number,
  pageSize: number,
): { items: Recommendation[]; nextOffset: number; hasMore: boolean } {
  const items = list.slice(offset, offset + pageSize);
  const nextOffset = offset + items.length;
  return {
    items,
    nextOffset,
    hasMore: nextOffset < list.length,
  };
}
