import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — WTW",
};

export default function TermsOfService() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 text-sm leading-7 text-foreground">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mb-10 text-muted-foreground">Last updated: May 10, 2026</p>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">1. Acceptance</h2>
        <p>
          By creating an account or using WTW (&ldquo;What To Watch&rdquo;, &ldquo;the Service&rdquo;),
          you agree to these Terms of Service. If you do not agree, do not use
          the Service. The Service is operated by Shahar Naor.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">2. Description of service</h2>
        <p>
          WTW is an AI-powered film and television recommendation engine. It
          builds a personalized taste profile based on your viewing history and
          ratings, and uses that profile to suggest films and TV shows. The
          Service is provided as-is and is currently in an early access phase.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">3. Eligibility</h2>
        <p>
          You must be at least 13 years old to use the Service. By using the
          Service, you represent that you meet this requirement.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">4. Your account</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>You are responsible for maintaining the security of your account.</li>
          <li>
            You must provide accurate information and keep it up to date.
          </li>
          <li>
            You may not share your account or use another person&rsquo;s account
            without permission.
          </li>
          <li>
            You are responsible for all activity that occurs under your account.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">5. Acceptable use</h2>
        <p className="mb-3">You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Use the Service for any unlawful purpose.</li>
          <li>
            Attempt to reverse-engineer, scrape, or extract data from the
            Service in bulk.
          </li>
          <li>
            Interfere with or disrupt the integrity or performance of the
            Service.
          </li>
          <li>
            Attempt to gain unauthorized access to any part of the Service or
            its related systems.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">6. Content and recommendations</h2>
        <p>
          Recommendations generated by WTW are produced by AI models and are
          provided for entertainment purposes only. We do not guarantee the
          accuracy, completeness, or suitability of any recommendation. Film and
          TV metadata is sourced from TMDB and OMDB; we are not responsible for
          errors in that data.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">7. Intellectual property</h2>
        <p>
          The Service, including its design, code, and AI models, is owned by
          Shahar Naor. Film titles, artwork, and metadata displayed in the
          Service belong to their respective rights holders. Your taste profile
          data belongs to you.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">8. Disclaimer of warranties</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties
          of any kind, either express or implied, including but not limited to
          warranties of merchantability, fitness for a particular purpose, or
          non-infringement. We do not warrant that the Service will be
          uninterrupted, error-free, or free of viruses.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">9. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, Shahar Naor shall not be
          liable for any indirect, incidental, special, consequential, or
          punitive damages arising from your use of the Service, even if advised
          of the possibility of such damages.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">10. Termination</h2>
        <p>
          We may suspend or terminate your account at any time if you violate
          these Terms. You may delete your account at any time by contacting us
          at{" "}
          <a href="mailto:shaharnaor@outlook.com" className="underline">
            shaharnaor@outlook.com
          </a>
          .
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-3 text-lg font-semibold">11. Changes to these terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the
          Service after changes are posted constitutes acceptance of the updated
          Terms. We will notify registered users of material changes by email.
        </p>
      </section>

      <section>
        <h2 className="mb-3 text-lg font-semibold">12. Contact</h2>
        <p>
          Questions about these Terms:{" "}
          <a href="mailto:shaharnaor@outlook.com" className="underline">
            shaharnaor@outlook.com
          </a>
        </p>
      </section>
    </main>
  );
}
